### ISSUE TITLE
下载过程中提示“页面不存在”错误 Sorry, that page does not exist","code":34

### ISSUE THREAD

**Issue by 7Luminaries** [unkmonster/tmd#21]
已经确认过X的auth_token和ct0都无误，之前运行都是正常的。
是X换了接口了吗？

INFO[2024-11-24T10:19:51+08:00] config is loaded
2024/11/24 10:19:51.981093 WARN RESTY {"errors":[{"message":"Sorry, that page does not exist","code":34}]}, Attempt 1
2024/11/24 10:19:51.981593 ERROR RESTY {"errors":[{"message":"Sorry, that page does not exist","code":34}]}
FATA[2024-11-24T10:19:51+08:00] failed to login: {"errors":[{"message":"Sorry, that page does not exist","code":34}]}

![image](https://github.com/user-attachments/assets/baa15508-b6a8-4300-b35a-6b45beba72f3)

**Comment by unkmonster** [comment]
对的，旧接口修改了鉴权方式，已修复

**Comment by yangsadd** [comment]
这个问题最新代码又出现了
