### ISSUE TITLE
TLS handshake timeout

### ISSUE THREAD

**Issue by Asheblog** [unkmonster/tmd#5]
已开梯子，ct和auth都在应用部分捕获并填写了，但仍失败。

![1723711238385](https://github.com/user-attachments/assets/5802c66d-3d58-4528-8e01-ca47b94015ed)

**Comment by unkmonster** [comment]
你的代理客户端有tun模式吗，你可以开tun模式

**Comment by unkmonster** [comment]
如果你的代理客户端不支持 TUN 代理，我刚刚提交了修复的代码，你可以通过在运行前设置环境变量来让程序走代理

```
set http_proxy=http://127.0.0.1:7890 & set https_proxy=http://127.0.0.1:7890
```
把 `http://127.0.0.1:7890` 替换成你自己的代理服务器的地址

**Comment by Asheblog** [comment]
谢谢。

**Comment by unkmonster** [comment]
不客气
