### ISSUE TITLE
我无法输入任何字符我该怎么办

### ISSUE THREAD

**Issue by liudimimei** [unkmonster/tmd#7]
![屏幕截图 2024-08-29 000838](https://github.com/user-attachments/assets/0526b35a-4e74-4c3b-a056-3e62fc1d8006)

**Comment by unkmonster** [comment]
你的意思是配置填写不了还是没法制定要下载的用户/列表？

**Comment by liudimimei** [comment]
我下载exe文件后正常输入配置列表并且配置成功后，再次点开该界面，但输入任何东西都无反应，请问一下这是怎么回事

**Comment by unkmonster** [comment]
你不该直接运行应用程序，应该通过命令行参数把要下载的用户/列表传递给应用程序

**Comment by liudimimei** [comment]
好的，不过可以麻烦您给我录个Windows的使用视频吗？我并不是很会用Python，或者哔站上发一个使用视频？我怕我又弄出新问题。我的邮箱是2200606629@qq.com

**Comment by unkmonster** [comment]
我加你qq吧
